// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: image.proto

#include "image.pb.h"
#include "image.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SendImage {

static const char* ImageServer_method_names[] = {
  "/SendImage.ImageServer/GetImage",
};

std::unique_ptr< ImageServer::Stub> ImageServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageServer::Stub> stub(new ImageServer::Stub(channel));
  return stub;
}

ImageServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetImage_(ImageServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImageServer::Stub::GetImage(::grpc::ClientContext* context, const ::SendImage::GetImageRequest& request, ::SendImage::GetImageReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetImage_, context, request, response);
}

void ImageServer::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::SendImage::GetImageRequest* request, ::SendImage::GetImageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, std::move(f));
}

void ImageServer::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SendImage::GetImageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, std::move(f));
}

void ImageServer::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::SendImage::GetImageRequest* request, ::SendImage::GetImageReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, reactor);
}

void ImageServer::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SendImage::GetImageReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SendImage::GetImageReply>* ImageServer::Stub::AsyncGetImageRaw(::grpc::ClientContext* context, const ::SendImage::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SendImage::GetImageReply>::Create(channel_.get(), cq, rpcmethod_GetImage_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::SendImage::GetImageReply>* ImageServer::Stub::PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::SendImage::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::SendImage::GetImageReply>::Create(channel_.get(), cq, rpcmethod_GetImage_, context, request, false);
}

ImageServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageServer::Service, ::SendImage::GetImageRequest, ::SendImage::GetImageReply>(
          std::mem_fn(&ImageServer::Service::GetImage), this)));
}

ImageServer::Service::~Service() {
}

::grpc::Status ImageServer::Service::GetImage(::grpc::ServerContext* context, const ::SendImage::GetImageRequest* request, ::SendImage::GetImageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SendImage

